[package]
name = "argvus-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
argvus-i18n.workspace = true
argvus-theme = { path = "../argvus-theme" }
crossterm.workspace = true
image.workspace = true
ratatui.workspace = true
ratatui-image.workspace = true
resvg.workspace = true
unicode-width.workspace = true
clap.workspace = true
serde_json = "1.0"

[[bin]]
name = "argvus-appearance"
path = "src/bin/argvus-appearance.rs"
